
# experiment.yaml
# Configuration for 5G throughput modeling and evaluation
# Created: 2025-10-14
# Author: Javier Albert-Smet

data:
  input_csv: "data/throughput.csv"
  target: "DL Throughput"
  log_transform_target: True
  norm_target: True
  carriers:
    - "CARRIER1"
    - "CARRIER2"
    - "CARRIER3"
  radio_access_technologies:
    - "4G"
    - "5G_NSA"
    - "5G_SA"
  features:
    - "Latency"          # network latency (ms)
    - "Jitter"           # variation in delay (ms)
    - "Packet Loss"      # packet loss rate (%)
    - "DL TTFB"          # downlink time to first byte (ms)
    - "RSRP"             # signal strength (dBm)
    - "RSRQ"             # signal quality (dB)
    - "SINR"             # signal-to-interference-plus-noise ratio (dB)
    - "Timing Advance"   # uplink timing offset (ms)
    - "Frequency Band"   # frequency band used (MHz)
    - "Carrier"          # carrier/operator ID (CARRIER1, CARRIER2, CARRIER3)
  temporal_encodings:
    - "Time of the Day"  # hour (0-23)
    - "Day of the Week"  # day (0-6)

experiment:
  output_dir: "artifacts"
  experiment_name: "2025-10-14_12-20-39" # Set to "" for a new experiment
  random_state: 42
  data_split_dates:
    train: 
      start: "2025-04-30"
      end: "2025-08-18"
    val:
      start: "2025-08-18"
      end: "2025-08-26"
    test: 
      start: "2025-08-26"
      end: "2025-09-10"

models:
  XGBoost:
    n_estimators: 1 # 1000
    patience: 1 # 100
    learning_rate: 0.05
  NGBoost:
    n_estimators: 1 # 1000
    patience: 1 # 100
    learning_rate: 0.05

eval:
  metrics:
    mae: True
    rmse: True
    r2: True
    mae_nat: True
    rmse_nat: True
  confidence_intervals:
    percentile: 0.95
    display_samples: 50

logging:
  level: "DEBUG" # options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
  datefmt: "%H:%M:%S"